# Site settings
title: Profilr
email: francois@firmapi.com
description: Trouver les meilleurs profils
baseurl:
url: http://fgrante.github.io/profilr
twitter_username: fgrante
github_username:  fgrante

# Build settings
markdown: kramdown
