# Site settings
title: Profilr
email: francois@firmapi.com
description: Find the best profiles on social networks instantly
baseurl:
url: https://profilr.co
twitter_username: _Firmapi

# Build settings
markdown: kramdown
