# Site settings
title: Profilr
email: francois@firmapi.com
description: Profilr is the easiest way to find profiles on social media.
baseurl:
url: https://profilr.co
twitter_username: EmailHunter

# Build settings
markdown: kramdown
