# Site settings
title: Profilr
email: francois@firmapi.com
description: "Trouver les meilleurs profils"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fgrante.github.io/profilr/" # the base hostname & protocol for your site
twitter_username: fgrante
github_username:  fgrante

# Build settings
markdown: kramdown
